name: flutter_mold_vault
description: "The vault of mold for Flutter Code"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  flutter_dotenv: ^5.2.1
  http: ^1.2.1
  get: ^4.6.6
  logger: ^2.5.0
  encrypt: ^5.0.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  # fonts:
  #   - family: FontFamilyName
  #     fonts:
  #       - asset: fonts/FontFile-400.ttf
  #         weight: 400
  #       - asset: fonts/FontFile-700.ttf
  #         weight: 700
  #   - family: FontFamilyNameOther
  #     fonts:
  #       - asset: fonts/FontFileOther-Bold.ttf
  #         weight: 700
